---
- functions:
  - {name: unsafePerformIO, within: []}  # unsafePerformIO can only appear in no modules
  - {name: error, within: [Web.Tweet.Sign, Web.Tweet.Parser, Web.Tweet.API]}
- ignore: {name: Use camelCase, within: Web.Tweet.Parser.FastParser}
