---
sudo: false
language: c
cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
addons:
  apt:
    packages:
      - libgmp3-dev
matrix:
  include:

    - env: TARGET=x86_64-unkown-linux-gnu
      addons:
        apt:
          update: true
          sources:
            - hvr-ghc
          packages:
            - ghc-8.6.4
            - cabal-install-2.4

    - env: TARGET=x86_64-apple-darwin
      os: osx

before_install:
  - |
    if [ `uname` = "Darwin" ]
    then
      brew install cabal-install
      cabal new-update
    else
      export PATH=/opt/ghc/bin:$PATH
      cabal new-update
    fi
  - export PATH=$HOME/.cabal/bin:$PATH

script:
  - cabal new-build
  - cabal new-test
  - |
    if [ `uname` = "Darwin" ]
    then
      export BINPATH="$(find dist-newstyle/ -name tweet -perm 755 | tail -n1)"
    else
      export BINPATH="$(find dist-newstyle/ -name tweet -executable | tail -n1)"
    fi
  - echo $BINPATH
  - mv $BINPATH tweet-$TARGET
  - strip tweet-$TARGET

deploy:
  api_key:
    secure: "Un0Ebl9I9CAEB+3CEeSz28oYRN138Nj65xZWTBc/qGjJVZM647N0LklDSmVU/Rq8IC/FqFQEQkT3kb6DJDgOgl8FTun9CkFB4IoHNKFuM7XLnhgMS6lBsKDFz6JVAZ6yHIEGzYlEn1EB2/ZDeBwrWAwfFl1/hq5V5vFaLIz5Pn5lEFrBjB6xmUrz0S+1bc8u0vyN2jxnhqSiX5G1bObxnN9i5gMzhgn2snWIZO4Ee6MRHS2Ru6XLMNoaEzyb7eG8rGxEJAct44GvcDeJbNX29X50QWGU9j/KIBPM8zF+WI6oIIs7NnHzOEfUNSb4MzfRdIoK8OyxwHfKqFl43pJKutvH69ovYnfw92Ka1WlO0ziIiOV3fupsXRIu91fqhPcvBHvdPkGq2x/OE56v3nHCHkc2MYGf4x8oM1Ml7w3RYZNcI2TdGo5s6jpCEukoLM27dRjYdtqVxB4CSoIrYbELTPXOMbQtTH+sxWDcu+keqvC6j/u4Jjk6TaiRt+Ftwz5UBI53Sjbf+UzmKjr2ICB65mItZM3pOCFloLtnRJFMxYkRSUAqwT0esrMZ61iJc2PJ2RLGIAJ3KDDr5pWoB+SR6K4p8MO/qYkGQugi77hoC3VlCnKOxYn69LsK2CSHvTUsbqPIZIwXD+RiFsWWW8dfWzR5DGEaLhfZExgQZKzUk0s="
  file: tweet-$TARGET
  on:
    tags: true
  provider: releases
  skip_cleanup: true

branches:
  only:
    - master
    - /\d+\.\d+\.\d+\.\d+.*$/
